apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1RENDQWN5Z0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFqTVJBd0RnWURWUVFLRXdkck0zTXQKYjNKbk1ROHdEUVlEVlFRREV3WnJNM010WTJFd0hoY05NVGt4TURBek1UTTFPREk0V2hjTk1qa3dPVE13TVRNMQpPREk0V2pBak1SQXdEZ1lEVlFRS0V3ZHJNM010YjNKbk1ROHdEUVlEVlFRREV3WnJNM010WTJFd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDOGNmaSt5and3VTlOYnl5eWlNbGRaZlJNajVQclgKdWt3MW9hczZsRFVaaTAyOVRqRUZCZmkzSVViNlcyQmIrdDV3amF1YWNJSnVjUzZJV2VHV2NKYWVIdElQdytqTwpBVFJncC90Qmt2SWtxcURrTWpLcXA3ZlNlTlVqM1FMeHFJc1BWRlNNUmkxV2RYSTBJNjZqa3QrL0lXakpnK1g0CmpwbVdOeHYzQzRJb25hRjY1SWFyckZiYi8wS2RReXpNeXEwR2U5MXFpMG9HWFhuOUNTZTBBdHhiKzdDd2YxSmYKQmNmVVY3dFlLTEU4WXFId0hIR1R4a2ZONy9ZZjNBOVJuUlM5aS84YnJ1ekRqRVZGTmszSDdvcTA4OWtCUWtMSQp0eU1WQUJiWWJRNVJhbzRCbHlaUUJWVHd2OXRPWnU3Z2JMVzRNcTUvcm1PWnhmTE80RTAxelZnQkFnTUJBQUdqCkl6QWhNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUFscXQ5MlVPSG1HZys3Szk3T3BIVGhSd29aQVhOSDBOVkpOZjF1TDRUak8xYTlEaDlxWDROcApEemxXemlTN3BHQWRVM2ZvZG1RM2V0NUN3c0xpVTAxNjk0QTJReklMaU1BeTQ4Tjd5Nnl3RXcvc2gvNjFwL2dpCkZUa3NMbW1oWWlrT2luZWRsWldFSlN6TjR2QWN1c0w3djh1WEZDdkIzNDg3SlEyNWN1TDVnMUVBZGJBQzVRYXcKZVVwNU1XbXJrc1F0eDRLZHdudWg1RmJBcG1xTkxrOEdRazRubXorcFZVOTFVdVpCWmZWRzJKdDFEUzNlaml6VwpNMk1CU1liT3l2cG1hVFQ1N3ZPdnZQMmFhUDdnNS9uVno5OXVpVWtxZVBWQmticVYwRUNZS08rNGJ0UkFkWEVOCnh2SFJSMHQzL1BpZFN6ZjRpYUtOSmllRytyNmt2UjRmCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://localhost:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 811990c13b5519ec4f7e4e8707d476a8
    username: admin
