apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1RENDQWN5Z0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFqTVJBd0RnWURWUVFLRXdkck0zTXQKYjNKbk1ROHdEUVlEVlFRREV3WnJNM010WTJFd0hoY05NVGt4TWpBMU1USTFPREEyV2hjTk1qa3hNakF5TVRJMQpPREEyV2pBak1SQXdEZ1lEVlFRS0V3ZHJNM010YjNKbk1ROHdEUVlEVlFRREV3WnJNM010WTJFd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEaTZpYnlyb0tkYVl5YTR1MFNMWWphcnJKZkcrSXYKM3FIaUNZUjVFUVZzUVVIcEtHVDZhL3R0S1hxY2pzRk53VXJSOFNuSDJJSUxLU1pqK1V0dEQ0Z3UybVJWTitFUAp2ZFVRbTNwVUtRZjh6Unp5ZnlsVEd3R3pkRm9YSmVpMXBHTExYditYN1poakJwaWNMYktBSEVmN21vNk8zcDVvCmRZQTlLem1hanlib3BoNnpJVEpEN3lWaEUvbkRRNG9vNzZWYkswQnZuZXhoc0FhQWpkQXhLb09pRkNhb0dNODEKUWlGZVJDZFhsUkZ5UVE5dk56ZEhXRlpWRHdxdC9QMUlUREZxWm1PSVlSSTQ1eENTVThUbDUxcHIwV1JTb0xYNQpEL3k3NWZyZnN5eVlTZEFHZlZQOGlhR2VFWklKbEhNTHJCd2J5VEVxbzdtS3VWMlBWbW15VHdFbEFnTUJBQUdqCkl6QWhNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUM2NWFWcjdiUWRkTGdHQkErbW9IVUFvTC9xUktsKzExRDFWQ3dKaHNSOUVHNzJad1pQQi9Lcwo5YkU5SEIrWjI5MnExWlB5c1IzVjNBZEVhSVRuT3dPYmdwalozV2RpUmNtUVVNU1BoOXQxTjdKWDZHUThwb0JWCkVWSiswMC9LTzBnZzBpaDJTa3JNcG9hREJjRVRzbG11TklNNytmcFpNTWo4Ykx3Y3h0RlRsL3lRc3FvYjJhNkIKell4NDdwMWZGMUZUU1JyZ1AyZXNvU1FRL3NWczU0ZE1YRnh4NmdMTjN5cmhMWnhPNHQ2RDRlZWtBSVVxNWRBTgpQVzJGZktMbUtoYXdjZ1owMmRqNzc0VGs3eHcxclpvVndZOGNwQXlHSk5ETldObWM1K3pDbHVyeVZhZUNvQWJwCi9Uc21CV1FCbEVPT0pPaXFBZmJ3STFMbDBXVmZqSXRYCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://localhost:6443
  name: default
contexts:
- context:
    cluster: default
    namespace: kube-system
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 05e882a552ea70e6f6a5a3327180e975
    username: admin
