apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1RENDQWN5Z0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFqTVJBd0RnWURWUVFLRXdkck0zTXQKYjNKbk1ROHdEUVlEVlFRREV3WnJNM010WTJFd0hoY05NVGt3T1RJMU1UTTFNVFUxV2hjTk1qa3dPVEl5TVRNMQpNVFUxV2pBak1SQXdEZ1lEVlFRS0V3ZHJNM010YjNKbk1ROHdEUVlEVlFRREV3WnJNM010WTJFd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDd2ExdWM0aFowY1E5dERWc1FiNmJtL1NMZ29Wcm8KZXNqbVRubUUvQnVEdGdIRjNMS1hZWWFsb2dneG56cjVGeVFkb3VlVlFLencva3BpcmVac2RVSFNEWHZJdC9rcwo3SGZNTkRORW54bVBMZG9ONElMNmZYV0k5WUNTUGlMaDEzdDI4RkdUcXh0SFFEcFV1NU4vdmhJSk1hQWxOeDhGCnlzL1FQK3c5ajhGNVVxaVozTVVWdnBYb3N0K0tJanhZU3JFdXg1ZmpKQ0V6aEVhTkVuL045M2ZGeEYvOWFGbzEKdmVmcXBaZXlZdmUwUS9RbVZidEdwbHA0c2pDR04weEFJaVFsQ2lVL0Z6UHJDYU9CQVEySm5VekF3MmtnS21uawpmd1BETFdxcVV0WTMxY0VNdjNpcms4aWhZM2VablYweEorVENDUHJGYnFZQ3RTRlVPWGlzR2RMNUFnTUJBQUdqCkl6QWhNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUExMTZKWHRWd3o2SVZyU1NPa0VxSjZtVnpDSUp4RGtxenVkTjA2RzErSTRackYzTTRoV1pSTAp3ZlN5NW5QOWVPV1JNckd6L0VIRzc3WWgwZ21mVTZKWmd6ZTJNOHRrU20vdGxGL2dPYUd0Z3lIOWFDaHh3d2dkCnpZVGQra3ZhRlBYZEZnRS9kM1VkUUpTVGNSSHZzYms2Zkg3dUxMTG8vNnJ6NzJMWDZidlcvQVhmOFlvNlh5dE4KeVFUajRzWElPZDVBTVJNTWdJR3RJa3JJY2xOcFRWQ2ZwdG1INkwwVk51bC9takVlSmZOYUhDWnl4dFVsdDNXVQpoSjh3OWRtNXBRdFJZYzJWemJJVVBqa1lneStoNTZ0VlR6elBZM21aZGtOREt2YUNWUGJjQlFZajhVUlcvb3VSCklyWUsrL0pUcUxsN1RMTjJZellLb0ZMWWE0b3hZS1JBCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://localhost:6443
  name: default
contexts:
- context:
    cluster: default
    namespace: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 2d32d635e26286e0f556052fb68c051d
    username: admin
