# http routing section
[http]
  [http.routers.flux]
     # Define a connection between requests and services
      rule = "Host(`fluxit.com.ar`)"
      # If the rule matches, applies the middleware
      # middlewares = ["test-user"]
      # If the rule matches, forward to the ingress\ service (declared below)
      service = "ingress"

  # [http.middlewares]
  #   # Define an authentication mechanism
  #   [http.middlewares.test-user.basicAuth]
  #     users = ["test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"]
